server:
  port: 8088
spring:
  application:
    name: service-edu
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/park?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis 配置
  redis:
    host: 120.25.223.229
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/zgz/park/mapper/xml/*.xml
  type-aliases-package: com.zgz.park.pojo
# 设置日志级别
logging:
  level:
    root: info
  #阿里云 OSS
  #不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: XXXXX
      keyid: XXXXXX
      keysecret: XXXXX
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: XXXXXX



